[package]
name = "magelang_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "8.0.0"
wasmtime-wasi = "8.0.0"
